const CHF = new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'});
const KEY='stweg_master_v1_premium';
const defaultState={
  view:'dashboard', budgetSoll:20150, budgetIst:9850, liquiditaet:11245, zielGuthaben:300,
  owners:[
    {id:'bianchi',name:'Renato Bianchi',saldo:-1155.69,paid:1855.69,app:540,my:540,profil:'Aufholbedarf Vorjahr'},
    {id:'nickel',name:'Alexander Nickel',saldo:-308.67,paid:3400,app:500,my:500,profil:'Nachforderung fast abgegolten'},
    {id:'balsano',name:'Angelo Balsano',saldo:-806.99,paid:3056.99,app:650,my:650,profil:'Hohe Heizkosten, Reserve sinnvoll'},
    {id:'rhein',name:'Thomas Rhein',saldo:283.35,paid:2400,app:350,my:350,profil:'Guthaben, tieferes Heizrisiko'},
    {id:'jermann',name:'Hans-Peter Jermann',saldo:664.42,paid:3000,app:250,my:300,profil:'Guthaben wird angerechnet'}],
  journal:[
    {date:'10.05.2026', text:'Heizölrechnung', cat:'Heizung', type:'Ausgabe', amount:-1245.50},
    {date:'09.05.2026', text:'Akontozahlung Bianchi', cat:'Akonto', type:'Einnahme', amount:550},
    {date:'08.05.2026', text:'Akontozahlung Nickel', cat:'Akonto', type:'Einnahme', amount:500},
    {date:'07.05.2026', text:'Hauswart April', cat:'Hauswart', type:'Ausgabe', amount:-450}],
  checks:['Journal geprüft','Bankkonto geprüft','Eigentümerkonten geprüft','Budget geprüft','Heizkostenabrechnung geprüft','Warmwasser geprüft','Wasser geprüft','Erneuerungsfonds geprüft','Belege vollständig','Jahresabschluss geprüft'],
  checked:{}, report:'Ich bestätige, dass ich die Rechnung geprüft habe und keine wesentlichen Beanstandungen festgestellt wurden.',
  decisions:['Jahresrechnung genehmigt','Revisorbericht genehmigt','Budget 2027 genehmigt','Akontozahlungen genehmigt','Entlastung Verwaltung']
};
let state=load();
const navItems=[['dashboard','📊','Dashboard'],['owners','👥','Eigentümer'],['journal','📖','Journal'],['budget','💰','Budget'],['docs','📂','Dokumente'],['revision','👨‍💼','Revision'],['meeting','📋','Versammlung']];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function totalOwners(){return state.owners.reduce((s,o)=>s+Number(o.my||0),0)}
function signed(n){return `${n>=0?'+':'-'} ${CHF.format(Math.abs(n))}`}
function setView(v){state.view=v; save(); render()}
function renderNav(){document.getElementById('nav').innerHTML=navItems.map(([id,ico,label])=>`<button class="nav-btn ${state.view===id?'active':''}" onclick="setView('${id}')"><span>${ico}</span>${label}</button>`).join('')}
function render(){renderNav(); const title=navItems.find(i=>i[0]===state.view)?.[2]||'Dashboard'; document.getElementById('pageTitle').textContent=title; document.getElementById('viewRoot').innerHTML=views[state.view](); bind()}
const views={
 dashboard(){const need=state.budgetSoll+state.owners.length*state.zielGuthaben; const yearly=totalOwners()*12; const pct=Math.round(state.budgetIst/state.budgetSoll*100); return `<div class="grid cards"><div class="card gold"><div class="label">Budget Soll</div><div class="value">${CHF.format(state.budgetSoll)}</div></div><div class="card"><div class="label">Budget Ist</div><div class="value">${CHF.format(state.budgetIst)}</div><div class="muted">${pct}% verbraucht</div></div><div class="card"><div class="label">Eigentümer</div><div class="value">5 / 5</div><div class="muted">Akonto aktiv</div></div><div class="card"><div class="label">Revision</div><div class="value green">Bereit</div><div class="muted">Link noch nicht freigegeben</div></div></div><br><div class="grid two"><div class="panel"><h3>Budget & Liquidität</h3><div class="bar"><span style="width:${pct}%"></span></div><p>${pct}% Budgetverbrauch · Jahresprognose Akonto ${CHF.format(yearly)} · Bedarf ${CHF.format(need)}</p></div><div class="panel"><h3>Heute</h3><p>🟡 2 Akontoempfehlungen prüfen</p><p>🟢 Journal aktuell</p><p>🟢 Dokumente vollständig</p><p>⚪ Revisor-Link erzeugen</p></div></div><br><div class="grid three">${state.owners.slice(1,4).map(o=>`<div class="card"><div class="label">${o.name.split(' ').pop()}</div><div class="value">${CHF.format(o.my)}</div><div class="muted">${o.profil}</div></div>`).join('')}</div>`},
 owners(){return `<div class="panel"><h3>Eigentümerkonten</h3><table class="owner-table"><thead><tr><th>Eigentümer</th><th>Startsaldo</th><th>Bezahlt</th><th>App</th><th>Mein Betrag</th><th>Status</th></tr></thead><tbody>${state.owners.map(o=>`<tr><td><b>${o.name}</b><br><span class="muted">${o.profil}</span></td><td class="${o.saldo>=0?'green':'red'}">${signed(o.saldo)}</td><td>${CHF.format(o.paid)}</td><td>${CHF.format(o.app)}</td><td><input class="amount" data-id="${o.id}" type="number" step="10" value="${o.my}"></td><td><span class="pill">✓ maßgebend</span></td></tr>`).join('')}</tbody></table></div>`},
 journal(){return `<div class="panel"><h3>Journal</h3><div class="form"><input id="jDate" placeholder="Datum"><input id="jText" placeholder="Text"><select id="jCat"><option>Akonto</option><option>Heizung</option><option>Hauswart</option><option>Unterhalt</option><option>Versicherung</option></select><select id="jType"><option>Einnahme</option><option>Ausgabe</option></select><input id="jAmount" type="number" placeholder="Betrag"><button class="primary" id="addJournal">Eintragen</button></div><table class="journal-table"><thead><tr><th>Datum</th><th>Text</th><th>Kategorie</th><th>Typ</th><th>Betrag</th></tr></thead><tbody>${state.journal.map((j,i)=>`<tr><td>${j.date}</td><td>${j.text}</td><td>${j.cat}</td><td>${j.type}</td><td class="${j.amount>=0?'green':'red'}">${CHF.format(j.amount)}</td></tr>`).join('')}</tbody></table></div>`},
 budget(){const cats=[['Heizung',6000,2450],['Warmwasser',2200,900],['Wasser',1600,650],['Versicherung',1350,675],['Hauswart',2800,1450],['Verwaltung',2400,1200],['Erneuerungsfonds',2800,0],['Sonstiges',1000,525]];return `<div class="grid cards"><div class="card gold"><div class="label">Gesamtbudget</div><div class="value">${CHF.format(state.budgetSoll)}</div></div><div class="card"><div class="label">Ist</div><div class="value">${CHF.format(state.budgetIst)}</div></div><div class="card"><div class="label">Mein Betrag / Monat</div><div class="value">${CHF.format(totalOwners())}</div></div><div class="card"><div class="label">Zielguthaben</div><div class="value">${CHF.format(state.owners.length*state.zielGuthaben)}</div></div></div><br><div class="grid two">${cats.map(c=>{let p=Math.min(100,Math.round(c[2]/c[1]*100));return `<div class="panel"><h3>${c[0]}</h3><b>${CHF.format(c[2])}</b> / ${CHF.format(c[1])}<div class="bar"><span style="width:${p}%"></span></div><p>${p}% verbraucht</p></div>`}).join('')}</div>`},
 docs(){return `<div class="panel"><h3>Digitale Jahresmappe 2026</h3><div class="doc-grid"><div class="doc">📁 Januar<br><span class="muted">Bank, Belege, Journal</span></div><div class="doc">📁 Quartal 1<br><span class="muted">Quartalsbericht</span></div><div class="doc">📁 Revision<br><span class="muted">Checkliste, Bericht, Freigabe</span></div><div class="doc">📄 Heizölrechnung.pdf</div><div class="doc">📄 Versicherung.pdf</div><div class="doc">➕ Datei hochladen</div></div></div>`},
 revision(){return `<div class="grid two"><div class="panel"><h3>Revisor-Checkliste</h3>${state.checks.map(c=>`<label class="check"><input type="checkbox" class="revCheck" data-c="${c}" ${state.checked[c]?'checked':''}> ${c}</label>`).join('')}</div><div class="panel"><h3>Revisorbericht</h3><textarea id="report">${state.report}</textarea><br><br><button class="primary" id="saveReport">Bericht speichern</button></div></div>`},
 meeting(){return `<div class="panel"><h3>Eigentümerversammlung 2026</h3>${state.decisions.map(d=>`<div class="meeting-item"><span>☑ ${d}</span><span class="muted">24.06.2026</span></div>`).join('')}<br><button class="primary">Versammlungspaket erzeugen</button></div>`}
};
function bind(){document.querySelectorAll('.amount').forEach(i=>i.onchange=e=>{const o=state.owners.find(x=>x.id===e.target.dataset.id);o.my=Number(e.target.value)||0;save();render()}); const add=document.getElementById('addJournal'); if(add)add.onclick=()=>{let a=Number(jAmount.value)||0;if(jType.value==='Ausgabe')a=-Math.abs(a);state.journal.unshift({date:jDate.value||new Date().toLocaleDateString('de-CH'),text:jText.value||'Neue Buchung',cat:jCat.value,type:jType.value,amount:a});state.budgetIst+=a<0?Math.abs(a):0;save();render()}; document.querySelectorAll('.revCheck').forEach(c=>c.onchange=e=>{state.checked[e.target.dataset.c]=e.target.checked;save()}); const rep=document.getElementById('saveReport'); if(rep)rep.onclick=()=>{state.report=document.getElementById('report').value;save();alert('Revisorbericht gespeichert')}; document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));}
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='stweg-master-backup.json';a.click()};
render();
